# Generated by Django 4.0 on 2021-12-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='너무 큰 사진은 올릴 수 없습니다.', upload_to='user_profile/%Y/%m/%d'),
        ),
    ]
